openapi: 3.0.0
info:
  title: Paraphraser API
  version: 1.0.0
  description: API for a paraphraser application

paths:
  /paraphrase:
    post:
      summary: Paraphrase text
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  paraphrasedText:
                    type: string