/**
 * Paraphraser API
 * API for a paraphraser application
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ParaphrasePost200Response model module.
 * @module model/ParaphrasePost200Response
 * @version 1.0.0
 */
class ParaphrasePost200Response {
    /**
     * Constructs a new <code>ParaphrasePost200Response</code>.
     * @alias module:model/ParaphrasePost200Response
     */
    constructor() { 
        
        ParaphrasePost200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ParaphrasePost200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ParaphrasePost200Response} obj Optional instance to populate.
     * @return {module:model/ParaphrasePost200Response} The populated <code>ParaphrasePost200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ParaphrasePost200Response();

            if (data.hasOwnProperty('paraphrasedText')) {
                obj['paraphrasedText'] = ApiClient.convertToType(data['paraphrasedText'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ParaphrasePost200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ParaphrasePost200Response</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['paraphrasedText'] && !(typeof data['paraphrasedText'] === 'string' || data['paraphrasedText'] instanceof String)) {
            throw new Error("Expected the field `paraphrasedText` to be a primitive type in the JSON string but got " + data['paraphrasedText']);
        }

        return true;
    }


}



/**
 * @member {String} paraphrasedText
 */
ParaphrasePost200Response.prototype['paraphrasedText'] = undefined;






export default ParaphrasePost200Response;

